version: "3.8"
services:
  php83:
    build:
      context: ./php
      dockerfile: php83
    container_name: php83
    restart: always
    volumes:
      - ./php-project:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php-project:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d
      - "./nginx/devcerts/php:/etc/nginx/certs/php"
      - "./nginx/devcerts/vue:/etc/nginx/certs/vue"
    depends_on:
      - php83
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: mysql-db
      MYSQL_ROOT_PASSWORD: root-password
    ports:
      - "3306:3306"
    command: --sql-mode=''
    volumes:
      - ./mysql-storage:/var/lib/mysql:rw
    user: mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root-password
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
